const http=require("http"),fs=require("fs"),path=require("path"),url=require("url"),crypto=require("crypto");
const root=__dirname,port=process.env.PORT||3000,DATA=path.join(root,"data"),BEHAVIORS=path.join(DATA,"behaviors.json"),PLANS=path.join(DATA,"plans.json"),RUNS=path.join(DATA,"runs.json");
const runner=require("./benchmark-runner"),specAdapters=require("./benchmark-adapters"),robotAdapters=require("./robot-adapters"),db=require("./db"),auth=require("./auth"),billing=require("./billing");
const load=p=>JSON.parse(fs.readFileSync(p,"utf8"));const send=(res,status,data,headers={})=>{res.writeHead(status,{"Content-Type":"application/json","Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,POST,DELETE,OPTIONS","Access-Control-Allow-Headers":"Content-Type,Authorization",...headers});res.end(JSON.stringify(data))};
const mime={".html":"text/html; charset=utf-8",".css":"text/css; charset=utf-8",".js":"text/javascript; charset=utf-8",".json":"application/json; charset=utf-8"};const body=req=>new Promise((ok,no)=>{let b="";req.on("data",d=>{b+=d;if(b.length>2e6)no(new Error("body too large"))});req.on("end",()=>ok(b));req.on("error",no)});
const rate=new Map();function limited(req){const k=(req.socket.remoteAddress||"unknown");const now=Date.now(),a=(rate.get(k)||[]).filter(t=>now-t<60000);a.push(now);rate.set(k,a);return a.length>120}function monthRuns(runs){const m=new Date().toISOString().slice(0,7);return runs.filter(r=>String(r.createdAt||"").slice(0,7)===m).length}
function planFor(u){return load(PLANS).find(p=>p.id===u.plan)||load(PLANS)[0]}async function user(req){return auth.sessionUser(req)}
async function requireUser(req,res){const u=await user(req);if(!u){send(res,401,{error:"Authentication required"});return null}return u}
function hashKey(k){return crypto.createHash("sha256").update(k).digest("hex")}
function serve(res,u){let p=decodeURIComponent(u.pathname);if(p==="/")p="/index.html";if(p.includes(".."))return send(res,400,{error:"Invalid path"});const f=path.join(root,p);if(!fs.existsSync(f)||!fs.statSync(f).isFile())return send(res,404,{error:"Not found"});res.writeHead(200,{"Content-Type":mime[path.extname(f)]||"application/octet-stream","Cache-Control":"public,max-age=300"});fs.createReadStream(f).pipe(res)}
async function main(){
 const dbState=await db.init();http.createServer(async(req,res)=>{const u=url.parse(req.url,true);if(req.method==="OPTIONS"){res.writeHead(204);return res.end()}if(limited(req))return send(res,429,{error:"Rate limit exceeded"});
 try{
  if(u.pathname==="/api/health")return send(res,200,{ok:true,service:"humanoidbehavior",version:"1.0.0",storage:dbState.mode,capabilities:["simulation","benchmark","real-benchmarking-contract","postgresql","authentication","api-keys","billing","robot-adapters","model-adapters"]}); if(u.pathname==="/api/readiness"){const databaseRequired=!!process.env.DATABASE_URL;const checks={storage:dbState.mode,databaseConfigured:!!process.env.DATABASE_URL,stripeConfigured:!!process.env.STRIPE_SECRET_KEY,simulationHarness:true,mujocoWorkflow:true};const ready=!databaseRequired||dbState.mode==="postgresql";return send(res,ready?200:503,{ok:ready,ready,checks});}
  if(u.pathname==="/api/behaviors"){let d=load(BEHAVIORS);if(u.query.q){const q=u.query.q.toLowerCase();d=d.filter(x=>(x.name+" "+x.description+" "+x.category).toLowerCase().includes(q))}return send(res,200,{data:d,count:d.length})}
  if(u.pathname.startsWith("/api/behaviors/")){const b=load(BEHAVIORS).find(x=>x.id===u.pathname.split("/").pop());return b?send(res,200,b):send(res,404,{error:"Behavior not found"})}
  if(u.pathname==="/api/plans")return send(res,200,{data:load(PLANS)});
  if(u.pathname==="/api/adapters")return send(res,200,{data:{...Object.fromEntries(Object.entries(specAdapters.adapters).map(([id,a])=>[id,{kind:a.kind||"spec"}])),...Object.fromEntries(Object.entries(robotAdapters.adapters).map(([id,a])=>[id,{kind:a.kind}]))}});
  if(u.pathname==="/api/auth/signup"&&req.method==="POST"){const x=JSON.parse(await body(req)||"{}");if(!x.email||!x.password||x.password.length<8)return send(res,400,{error:"Email and password (8+ chars) required"});if(await db.findUserByEmail(x.email))return send(res,409,{error:"Account already exists"});const u=await db.createUser({id:db.id(),email:x.email.toLowerCase(),name:x.name||x.email.split("@")[0],passwordHash:await auth.hashPassword(x.password),plan:"free",createdAt:new Date().toISOString()});return send(res,201,{token:auth.createSession(u),user:{id:u.id,email:u.email,name:u.name,plan:u.plan}})}
  if(u.pathname==="/api/auth/login"&&req.method==="POST"){const x=JSON.parse(await body(req)||"{}"),u=await db.findUserByEmail(x.email||"");if(!u||!(await auth.verifyPassword(x.password||"",u.password_hash||u.passwordHash)))return send(res,401,{error:"Invalid credentials"});return send(res,200,{token:auth.createSession(u),user:{id:u.id,email:u.email,name:u.name,plan:u.plan}})}
  if(u.pathname==="/api/auth/demo"&&req.method==="POST"&&!process.env.DISABLE_DEMO_AUTH){const u={id:"demo_"+crypto.randomBytes(5).toString("hex"),email:"demo@example.invalid",name:"Demo Developer",plan:"free"};return send(res,200,{token:auth.createSession(u),user:u})}
  if(u.pathname==="/api/me"){const u=await requireUser(req,res);if(!u)return;return send(res,200,{user:u,plan:planFor(u),storage:dbState.mode})}
  if(u.pathname==="/api/keys"&&req.method==="GET"){const u=await requireUser(req,res);if(!u)return;return send(res,200,{data:await db.listKeys(u.id)})}
  if(u.pathname==="/api/keys"&&req.method==="POST"){const u=await requireUser(req,res);if(!u)return;const p=planFor(u),keys=await db.listKeys(u.id);if(p.limits.apiKeys>=0&&keys.length>=p.limits.apiKeys)return send(res,403,{error:"API key limit reached"});const raw="hb_live_"+crypto.randomBytes(24).toString("hex");await db.createKey({id:db.id(),userId:u.id,hash:hashKey(raw),prefix:raw.slice(0,15),name:(JSON.parse(await body(req)||"{}").name||"Default key"),createdAt:new Date().toISOString()});return send(res,201,{key:raw,message:"Store this key now. It will not be shown again."})}
  if(u.pathname.startsWith("/api/keys/")&&req.method==="DELETE"){const u=await requireUser(req,res);if(!u)return;return send(res,(await db.revokeKey(u.pathname.split("/").pop(),u.id))?200:404,{ok:true})}
  if(u.pathname==="/api/usage"){const u=await requireUser(req,res);if(!u)return;const runs=await db.listRuns(u.id),p=planFor(u);return send(res,200,{plan:p.id,limits:p.limits,usage:{benchmarksThisMonth:runs.filter(r=>String(r.createdAt||"").slice(0,7)===new Date().toISOString().slice(0,7)).length,apiKeys:(await db.listKeys(u.id)).length}})}
  if(u.pathname.startsWith("/api/runs/")&&req.method==="GET"){const u=await requireUser(req,res);if(!u)return;const id=u.pathname.split("/").pop();const run=await db.getRun(id,u.id);return run?send(res,200,run):send(res,404,{error:"Run not found"})}
  if(u.pathname==="/api/runs"&&req.method==="GET"){const u=await requireUser(req,res);if(!u)return;return send(res,200,{data:await db.listRuns(u.id)})}
  if(u.pathname==="/api/experiments/run"&&req.method==="POST"){const u=await requireUser(req,res);if(!u)return;const p=planFor(u),existing=await db.listRuns(u.id),experiments=await db.listExperiments(u.id),used=monthRuns(existing)+experiments.filter(e=>e.status==="completed"&&String(e.createdAt||"").slice(0,7)===new Date().toISOString().slice(0,7)).reduce((n,e)=>n+Number(e.result?.runCount||0),0),x=JSON.parse(await body(req)||"{}"),seeds=Array.isArray(x.seeds)?x.seeds.map(String):String(x.seeds||"42,1337,2026,7,99").split(",").map(s=>s.trim()).filter(Boolean),policies=Array.isArray(x.policies)&&x.policies.length?x.policies.map(String):["policy-a","policy-b"],seconds=Math.max(0.1,Math.min(Number(x.seconds||5),60)),engine=x.engine||"simulation-harness";if(!["simulation-harness","MuJoCo"].includes(engine))return send(res,400,{error:"Unsupported experiment engine"});if(seeds.length>20)return send(res,400,{error:"Maximum 20 seeds per experiment"});const requested=seeds.length*policies.length;if(p.limits.benchmarksPerMonth>=0&&used+requested>p.limits.benchmarksPerMonth)return send(res,429,{error:"Monthly benchmark limit reached",limit:p.limits.benchmarksPerMonth,used,requested});const id= db.id(),jobId=db.id(),createdAt=new Date().toISOString();const e={id,userId:u.id,benchmark:x.benchmark||"humanoid-behavior-experiment",engine,status:"queued",createdAt,result:{schemaVersion:"1.0",benchmark:x.benchmark||"humanoid-behavior-experiment",environment:x.environment||"hb-humanoid-v1",engine,measured:false,simulation:true,targetSeconds:seconds,runCount:0,expectedRunCount:seeds.length*policies.length,validation:{passed:false,message:"Experiment queued"},seeds,policies,rawResults:[],summary:{}}};await db.saveExperiment(e);await db.enqueueJob({id:jobId,experimentId:id,userId:u.id,type:"experiment",status:"queued",payload:{behaviorId:x.behaviorId||"pick-place",environment:x.environment||"hb-humanoid-v1",seconds,seeds,policies,engine}});e.jobId=jobId;await db.saveExperiment(e);return send(res,202,e);}
  if(u.pathname==="/api/experiments"&&req.method==="GET"){const u=await requireUser(req,res);if(!u)return;return send(res,200,{data:await db.listExperiments(u.id)});}
  if(u.pathname==="/api/experiments/compare"&&req.method==="GET"){const u=await requireUser(req,res);if(!u)return;const ids=String(u.query.ids||"").split(",").map(x=>x.trim()).filter(Boolean).slice(0,10);if(ids.length<2)return send(res,400,{error:"Provide at least two experiment ids"});const items=[];for(const id of ids){const e=await db.getExperiment(id,u.id);if(e)items.push(e)}return send(res,200,{data:items});}
  if(u.pathname.startsWith("/api/experiments/")&&u.pathname.endsWith("/artifacts")&&req.method==="GET"){const u=await requireUser(req,res);if(!u)return;const id=u.pathname.split("/")[3];return send(res,200,{data:await db.listArtifacts(id,u.id)});}
  if(u.pathname.startsWith("/api/experiments/")&&req.method==="GET"){const u=await requireUser(req,res);if(!u)return;const id=u.pathname.split("/").pop();const e=await db.getExperiment(id,u.id);return e?send(res,200,e):send(res,404,{error:"Experiment not found"});}
  if(u.pathname.startsWith("/api/jobs/")&&req.method==="GET"){const u=await requireUser(req,res);if(!u)return;const id=u.pathname.split("/").pop();const j=await db.getJob(id,u.id);return j?send(res,200,j):send(res,404,{error:"Job not found"});}

  if(u.pathname==="/api/experiments"&&req.method==="POST"){const u=await requireUser(req,res);if(!u)return;const x=JSON.parse(await body(req)||"{}");if(!x.benchmark||!x.engine||!x.result)return send(res,400,{error:"benchmark, engine and result required"});const e={id:db.id(),userId:u.id,benchmark:x.benchmark,engine:x.engine,status:x.status||"completed",result:x.result,createdAt:new Date().toISOString()};await db.saveExperiment(e);return send(res,201,e);}
  if(u.pathname==="/api/simulation/compare"&&req.method==="POST"){const u=await requireUser(req,res);if(!u)return;const x=JSON.parse(await body(req)||"{}");const sim=require("./simulation-benchmark");const a=sim.run({behaviorId:"pick-place",model:"policy-a",environment:"hb-humanoid-v1",seed:x.seed||"42"}),b=sim.run({behaviorId:"pick-place",model:"policy-b",environment:"hb-humanoid-v1",seed:x.seed||"42"});return send(res,200,{benchmark:"humanoid-stand-v1",engine:"simulation-harness",measured:false,reproducible:true,seed:String(x.seed||"42"),results:[a,b]})}
  if(u.pathname==="/api/simulation"&&req.method==="POST"){const u=await requireUser(req,res);if(!u)return;const x=JSON.parse(await body(req)||"{}");const sim=require("./simulation-benchmark");const result=sim.run(x);result.userId=u.id;result.adapter="simulation-harness";await db.saveRun(result);return send(res,200,result)}
  if(u.pathname==="/api/benchmark"&&req.method==="POST"){const u=await requireUser(req,res);if(!u)return;const x=JSON.parse(await body(req)||"{}"),p=planFor(u),runs=await db.listRuns(u.id),month=runs.filter(r=>String(r.createdAt||"").slice(0,7)===new Date().toISOString().slice(0,7));if(p.limits.benchmarksPerMonth>=0&&month.length>=p.limits.benchmarksPerMonth)return send(res,429,{error:"Monthly benchmark limit reached",limit:p.limits.benchmarksPerMonth});const b=load(BEHAVIORS).find(v=>v.id===x.behaviorId);if(!b)return send(res,404,{error:"Behavior not found"});const result=runner.evaluate(x);result.id=result.runId;result.userId=u.id;result.behaviorId=x.behaviorId;result.model=x.model||x.policy||null;result.adapter=x.adapter||"spec-validator";if(robotAdapters.adapters[result.adapter])result.adapterResult=await robotAdapters.runAdapter(result.adapter,{...x,behavior:b});else result.adapterResult=await specAdapters.runAdapter(result.adapter,{behavior:b,input:x});await db.saveRun(result);return send(res,200,result)}
  if(u.pathname==="/api/billing/checkout"&&req.method==="POST"){const u=await requireUser(req,res);if(!u)return;const x=JSON.parse(await body(req)||"{}");const s=await billing.checkout({user:u,plan:x.plan,successUrl:x.successUrl||"http://localhost:3000/dashboard.html",cancelUrl:x.cancelUrl||"http://localhost:3000/pricing.html"});return send(res,200,{url:s.url,id:s.id})}
  if(u.pathname==="/api/billing/webhook"&&req.method==="POST"){const raw=await body(req),event=billing.webhook(raw,req.headers["stripe-signature"]);return send(res,200,{received:true,type:event.type})}
  serve(res,u);
 }catch(e){send(res,400,{error:e.message||"Bad request"})}}).listen(port,()=>console.log("HumanoidBehavior API v1.0.0 listening on "+port))}
main().catch(e=>{console.error(e);process.exit(1)});