const HB={behaviors:[
{id:"pick-place",name:"Pick & Place",category:"Manipulation",level:"Core",description:"Pick a specified object and place it at a target location.",steps:["Perceive target object","Navigate to workspace","Reach and grasp","Transport object","Release at target","Verify placement"],metrics:{success:94,time:8.2,collision:1.4,recovery:87}},
{id:"open-door",name:"Open a Door",category:"Whole-body",level:"Interaction",description:"Approach a door, operate its handle and pass through safely.",steps:["Detect door and handle","Align body","Grasp handle","Apply force","Rotate/pull","Pass through and verify"],metrics:{success:89,time:12.7,collision:2.1,recovery:81}},
{id:"follow-person",name:"Follow a Person",category:"Navigation",level:"Social",description:"Track a moving person while maintaining a safe distance.",steps:["Detect person","Estimate motion","Set following distance","Plan collision-free path","Track and adapt","Recover if target is lost"],metrics:{success:91,time:18.4,collision:.8,recovery:93}},
{id:"handover",name:"Hand Object to Person",category:"Interaction",level:"Bimanual",description:"Move an object into a human's reachable handover zone.",steps:["Detect object","Grasp securely","Detect recipient","Predict handover pose","Transfer object","Confirm release"],metrics:{success:86,time:10.1,collision:1.1,recovery:79}}
]};
HB.runs=()=>JSON.parse(localStorage.getItem("hb_runs")||"[]");
HB.save=r=>{const a=HB.runs();a.unshift(r);localStorage.setItem("hb_runs",JSON.stringify(a.slice(0,100)))};
HB.card=b=>'<a class="behavior-card" href="behavior.html?id='+b.id+'"><div class="card-top"><span class="icon">'+b.name[0]+'</span><span class="pill">'+b.category+'</span></div><h3>'+b.name+'</h3><p>'+b.description+'</p><div class="card-bottom"><span>'+b.level+'</span><strong>'+b.metrics.success+'% baseline</strong></div></a>';
function library(){const root=document.querySelector("#behavior-list");if(!root)return;const q=(document.querySelector("#search")?.value||"").toLowerCase(),cat=document.querySelector("#category")?.value||"all";root.innerHTML=HB.behaviors.filter(b=>(cat==="all"||b.category===cat)&&(b.name+" "+b.description).toLowerCase().includes(q)).map(HB.card).join("")||'<div class="empty">No behaviors found.</div>'}
function detail(){const root=document.querySelector("#behavior-detail");if(!root)return;const id=new URLSearchParams(location.search).get("id")||"pick-place",b=HB.behaviors.find(x=>x.id===id)||HB.behaviors[0];root.innerHTML='<div class="eyebrow">BEHAVIOR SPECIFICATION</div><h1>'+b.name+'</h1><p class="lead">'+b.description+'</p><div class="detail-grid"><section><h2>Task sequence</h2><ol class="step-list">'+b.steps.map((s,i)=>'<li><b>0'+(i+1)+'</b><span>'+s+'</span></li>').join("")+'</ol></section><section><h2>Baseline metrics</h2><div class="metric-grid"><div><strong>'+b.metrics.success+'%</strong><span>Success</span></div><div><strong>'+b.metrics.time+'s</strong><span>Time</span></div><div><strong>'+b.metrics.collision+'%</strong><span>Collision</span></div><div><strong>'+b.metrics.recovery+'%</strong><span>Recovery</span></div></div></section></div><div class="runner"><div><div class="eyebrow">BENCHMARK RUNNER</div><h2>Evaluate this behavior</h2><p>Run a reproducible local specification check. Results are stored in this browser.</p></div><button class="button primary" id="run-btn">Run evaluation</button><div id="run-result" class="run-result"></div></div>';document.querySelector("#run-btn").onclick=()=>{const out=document.querySelector("#run-result");out.innerHTML='<span class="spinner"></span> Evaluating…';setTimeout(()=>{HB.save({id:Date.now(),behaviorId:b.id,behavior:b.name,status:"passed",metrics:b.metrics,createdAt:new Date().toISOString()});out.innerHTML='<b>Passed</b><span>'+b.steps.length+'/'+b.steps.length+' steps validated · '+b.metrics.success+'% baseline</span>'},650)}}
function dashboard(){const root=document.querySelector("#runs");if(!root)return;const a=HB.runs();root.innerHTML=a.length?a.map(r=>'<div class="run-row"><span>'+r.behavior+'</span><span>'+new Date(r.createdAt).toLocaleString()+'</span><strong>'+r.status+'</strong><span>'+r.metrics.success+'%</span></div>').join(""):'<div class="empty">No evaluations yet. Run a behavior to populate your workspace.</div>'}
function builder(){const form=document.querySelector("#builder-form");if(!form)return;form.onsubmit=e=>{e.preventDefault();const task=document.querySelector("#task").value.trim();const t=task.toLowerCase();const b=t.includes("door")?HB.behaviors[1]:t.includes("follow")?HB.behaviors[2]:t.includes("hand")?HB.behaviors[3]:HB.behaviors[0];document.querySelector("#builder-output").innerHTML='<div class="builder-result"><div class="eyebrow">GENERATED SPECIFICATION</div><h2>'+task.replace(/</g,"&lt;")+'</h2><ol class="step-list">'+b.steps.map((s,i)=>'<li><b>0'+(i+1)+'</b><span>'+s+'</span></li>').join("")+'</ol><a class="button primary" href="behavior.html?id='+b.id+'">Open behavior</a></div>'}}
document.addEventListener("DOMContentLoaded",()=>{library();detail();dashboard();builder();document.querySelector("#search")?.addEventListener("input",library);document.querySelector("#category")?.addEventListener("change",library)});
async function apiBenchmark(behaviorId,steps){const t=localStorage.getItem("hb_token");if(!t)throw new Error("Please sign in");const r=await fetch("/api/benchmark",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+t},body:JSON.stringify({behaviorId,completedSteps:steps,model:"browser-spec"})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Benchmark failed");return d}
HB.apiBenchmark=apiBenchmark;

function enhanceBuilderPackage(){const form=document.querySelector("#builder-form");if(!form)return;form.addEventListener("submit",()=>{setTimeout(()=>{const task=document.querySelector("#task")?.value.trim();const t=(task||"").toLowerCase();const b=t.includes("door")?HB.behaviors[1]:t.includes("follow")?HB.behaviors[2]:t.includes("hand")?HB.behaviors[3]:HB.behaviors[0];const pkg={schemaVersion:"1.0",id:"generated-"+b.id,version:"1.0.0",name:task,category:b.category,description:task,steps:b.steps,metrics:b.metrics,visibility:"private",compatibleEngines:["simulation-harness","MuJoCo"],compatibleRobots:["generic-humanoid"],provenance:{source:"Behavior Builder",generatedAt:new Date().toISOString()}};const preview=document.querySelector("#package-preview");if(preview){preview.hidden=false;document.querySelector("#package-json").textContent=JSON.stringify(pkg,null,2);document.querySelector("#copy-package").onclick=()=>navigator.clipboard.writeText(JSON.stringify(pkg,null,2))}},0)})}
document.addEventListener("DOMContentLoaded",enhanceBuilderPackage);
